### ISSUE TITLE
Which version of Wikidata?

### ISSUE THREAD

**Issue by minafarid** [patrickhoefler/wikidata-virtuoso#1]
What RDF dump files does it download from wikidata? 
Does it get the latest version?

**Comment by minafarid** [comment]
Never mind, I found it in the download-and-process.py file.
I think it is a better idea to automatically grab the latest version of Wikidata.

**Comment by patrickhoefler** [comment]
I completely agree, but since there is currently no ```latest``` folder for the RDF exports, I just didn't put in the effort. However, pull requests are always welcome :)
